name: prompter_cli
version: 0.0.1
description: This is for CLI wizards
repository: https://github.com/MajiMura/Prompter-CLI

environment:
  sdk: '>=2.10.0 <3.0.0'

  dependencies:
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0